### ISSUE TITLE
GetExchangeInfoAsync() fails

### ISSUE THREAD

**Issue by Anton-a235** [JKorf/Binance.Net#1007]
SpotApi.ExchangeData.GetExchangeInfoAsync() fails with this error:

```
{: Deserialize Unknown Exception: ArgumentNullException - Value cannot be null. (Parameter 'item')
   at System.Collections.Generic.List`1.System.Collections.IList.Add(Object item)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at CryptoExchange.Net.BaseClient.DeserializeAsync[T](Stream stream, JsonSerializer serializer, Nullable`1 requestId, Nullable`1 elapsedMilliseconds)
 [Data only available in Debug LogLevel]}
```

**Comment by HypsyNZ** [comment]
Oh good, its not just me

Its my birthday today, How annoying.

**Comment by Anton-a235** [comment]
Happy birthday! 
It's very strange... Is there a bug in Binance.Net?

**Comment by jdponomarev** [comment]
@HypsyNZ Happy birthday! Any ideas guys?

**Comment by jdponomarev** [comment]
there's some serialization issue, maybe something changed on binance side

**Comment by Anton-a235** [comment]
Has anyone else encountered this? Everything was fine an hour ago.

**Comment by jdponomarev** [comment]
yeah it started like 1hr ago...

**Comment by Anton-a235** [comment]
And updating Binance.Net from 7 to 8 didn't help.

**Comment by HypsyNZ** [comment]
The `reader` is null still trying to figure out why.

**Comment by HypsyNZ** [comment]
![https://i.imgur.com/AdC60ii.png](https://i.imgur.com/AdC60ii.png)

Binance is sending an empty response on purpose

**Comment by HypsyNZ** [comment]
Its probably because the library doesn't send any kind of user agent

I wouldn't be surprised if binance changed some firewall rules and just rekt everyone

**Comment by jdponomarev** [comment]
AXSBIDR coin has new permission type

**Comment by HypsyNZ** [comment]
That doesn't explain why the response is null

**Comment by jdponomarev** [comment]
TRD_GRP_003

**Comment by jdponomarev** [comment]
it can't be parsed, it's not on the permission enum

**Comment by HypsyNZ** [comment]
Why would that make the `Content` null, its the raw response

**Comment by jdponomarev** [comment]
it's not null, the response is there, but it can't be deserialized

**Comment by HypsyNZ** [comment]
`            new KeyValuePair<AccountType, string>(AccountType.TRD_GRP_002, "TRD_GRP_002"),`

Fixes the error

**Comment by Sarmaad** [comment]
> 

yep.. this is what we just did to patch our system.

**Comment by HypsyNZ** [comment]
Thanks everyone

**Comment by diegoaraujolima** [comment]
I made the modification but when compiling and using it gives the following error:

---------------------------

---------------------------
Could not load CryptoExchange.Net.Objects.BaseSocketClientOptions type from CryptoExchange.Net assembly, Version=4.2.8.0, Culture=neutral, PublicKeyToken=null.
---------------------------
OK
---------------------------

**Comment by JozefGula** [comment]
@JKorf can we expect a quick update for nuget?

**Comment by HypsyNZ** [comment]
@JKorf  This is a breaking bug

**Comment by JKorf** [comment]
Hi everyone, I just woke up so sorry for a bit of a delay. I've added the missing enum value as suggested and it fixes the issue. The new version 8.0.3 should be available in a bit.
Thanks for investigating the issue.

**Comment by d6665f** [comment]
Started happening again with TRD_GRP_004.
Thank you for your excellent work.

**Comment by hossamnew** [comment]
![image](https://user-images.githubusercontent.com/3645637/178438256-ff1f8aaf-cf1e-4344-a7f3-607a51a6bd95.png)

It's happening again, Thanks for your support

**Comment by jdponomarev** [comment]
@hossamnew what's the fix?

**Comment by hossamnew** [comment]
> @hossamnew what's the fix?

Consume the API by yourself 
https://api.binance.com/api/v3/exchangeInfo?symbol=BTCUSDT

or just wait for @JKorf  to add missing Enum and release update to fix this issue

**Comment by JKorf** [comment]
Should be fixed with 8.1.5
I also adjusted the deserialization so it doesn't fail the deserialization entirely when a new account type is added, but a warning is logged instead

**Comment by HypsyNZ** [comment]
This fails to deserialize `Exception: Unexpected character encountered while parsing value:`

I [made a different way of doing the same thing](https://github.com/HypsyNZ/BinanceAPI.NET/commit/0618a5bb9f407a71b8fdabdf02de299b5e920117) you are doing which is faster, I could make a PR if you want

**Comment by michcan52** [comment]
im having the same issue today, do you guys know anything about trhis?

**Comment by msanlisavas** [comment]
> im having the same issue today, do you guys know anything about this?

New version is released to fix the issue. Try updating.

**Comment by nemtajo** [comment]
I am still getting the same error with the latest nuget package, version 8.5.1.

**Comment by CamradZ** [comment]
Hi, how to resolve this problem?
![Screenshot_1](https://github.com/JKorf/Binance.Net/assets/143878924/52b4c4c8-c3be-4d72-9d47-c5ab791ad04a)
"Deserialize Unknown Exception: IOException" where i try to use "SpotApi.ExchangeData.GetExchangeInfoAsync" method.

**Comment by glipitch** [comment]
Which version of Binance.Net are you using?

**Comment by CamradZ** [comment]
8.4.4

**Comment by glipitch** [comment]
When Binance update their API, clients become out of date. This is why you see errors. The solution is to not use old versions.
