### ISSUE TITLE
GetExchangeInfo

### ISSUE THREAD

**Issue by muteddisk** [JKorf/Binance.Net#103]
Hi,

I'm having issue with the GetExchangeInfo for a couple of days now. This the output from the debugger. It doesn't happen all the time but I would say 1 out of 2.

Thanks for looking into it.
Best regards,

2018/07/19 02:19:28:269 | Info | User stream started
2018/07/19 02:19:30:754 | Info | Started stream for Binance.Net.Objects.BinanceStreamTick
2018/07/19 02:19:31:639 | Info | Started combined stream of type Binance.Net.Objects.BinanceStreamDepth
2018/07/19 02:19:33:062 | Info | Trade rules updated
The thread 0x2fb8 has exited with code 0 (0x0).
The thread 0x3338 has exited with code 0 (0x0).
2018/07/19 02:21:01:489 | Info | User stream started
2018/07/19 02:21:07:060 | Info | Started stream for Binance.Net.Objects.BinanceStreamTick
2018/07/19 02:21:07:961 | Info | Started combined stream of type Binance.Net.Objects.BinanceStreamDepth
2018/07/19 02:21:09:322 | Error | Deserialize JsonSerializationException: Error converting value "REQUEST_WEIGHT" to type 'Binance.Net.Objects.RateLimitType'. Path 'rateLimits[0].rateLimitType', line 1, position 92.. Received data: {"timezone":"UTC","serverTime":1531981269030,"rateLimits":[{"rateLimitType":"REQUEST_WEIGHT","interval":"MINUTE","limit":1200},{"rateLimitType":"ORDERS","interval":"SECOND","limit":10},{"rateLimitType":"ORDERS","interval":"DAY","limit":100000}],"exchangeFilters":[],"symbols":[{"symbol":"ETHBTC","status":"TRADING","baseAsset":"ETH","baseAssetPrecision":8,"quoteAsset":"BTC","quotePrecision":8,"orderTypes":["LIMIT","LIMIT_MAKER","MARKET","STOP_LOSS_LIMIT","TAKE_PROFIT_LIMIT"],"icebergAllowed":false,"filters":[{"filterType":"PRICE_FILTER","minPrice":"0.00648800","maxPrice":"0.64875000","tickSize":"0.00000100"},{"filterType":"LOT_SIZE","minQty":"0.00100000","maxQty":"100000.00000000","stepSize":"0.00100000"},{"filterType":"MIN_NOTIONAL","minNotional":"0.00100000"},{"filterType":"MAX_NUM_ALGO_ORDERS","maxNumAlgoOrders":5}]},{"symbol":"LTCBTC","status":"TRADING","baseAsset":"LTC","baseAssetPrecision":8,"quoteAsset":"BTC","quotePrecision":8,"orderTypes":["LIMIT","LIMIT_MAKER","MARKET","STOP_LOSS_LIMIT","TAKE_PROFIT_LIMIT"],"icebergAllowed":false,"filters":[{"filterType":"PRICE_FILTER","minPrice":"0.00118400","maxPrice":"0.11835000","tickSize":"0.00000100"},{"filterType":"LOT_SIZE","minQty":"0.01000000","maxQty":"100000.00000000","stepSize":"0.01000000"},{"filterType":"MIN_NOTIONAL","minNotional":"0.00100000"},{"filterType":"MAX_NUM_ALGO_ORDERS","maxNumAlgoOrders":5}]},{"symbol":"BNBBTC","status":"TRADING","baseAsset":"BNB","baseAssetPrecision":8,"quoteAsset":"BTC","quotePrecision":8,"orderTypes":["LIMIT","LIMIT_MAKER","MARKET","STOP_LOSS_LIMIT","TAKE_PROFIT_LIMIT"],"icebergAllowed":false,"filters":[{"filterType":"PRICE_FILTER","minPrice":"0.00017510","maxPrice":"0.01750950","tickSize":"0.00000010"},{"filterType":"LOT_SIZE","minQty":"0.01000000","maxQty":"90000000.00000000","stepSize":"0.01000000"},{"filterType":"MIN_NOTIONAL","minNotional":"0.00100000"},{"filterType":"MAX_NUM_ALGO_ORDERS","maxNumAlgoOrders":5}]},{"symbol":"NEOBTC","status":"TRADING","baseAsset":"NEO","baseAssetPrecision":8,"quoteAsset":"BTC","quotePrecision":8,"orderTypes":["LIMIT","LIMIT_MAKER","MARKET","STOP_LOSS_LIMIT","TAKE_PROFIT_LIMIT"],"icebergAllowed":false,"filters":[{"filterType":"PRICE_FILTER","minPrice":"0.00050300","maxPrice":"0.05023000","tickSize":"0.00000100"},{"filterType":"LOT_SIZE","minQty":"0.01000000","maxQty":"100000.00000000","stepSize":"0.01000000"},{"filterType":"MIN_NOTIONAL","minNotional":"0.00100000"},{"filterType":"MAX_NUM_ALGO_ORDERS","maxNumAlgoOrders":5}]},{"symbol":"QTUMETH","status":"TRADING","baseAsset":"QTUM","baseAssetPrecision":8,"quoteAsset":"ETH","quotePrecision":8,"orderTypes":["LIMIT","LIMIT_MAKER","MARKET","STOP_LOSS_LIMIT","TAKE_PROFIT_LIMIT"],"icebergAllowed":false,"filters":[{"filterType":"PRICE_FILTER","minPrice":"0.00177700","maxPrice":"0.17765000","tickSize":"0.00000100"},{"filterType":"LOT_SIZE","minQty":"0.01000000","maxQty":"90000000.00000000","stepSize":"0.01000000"},{"filterType":"MIN_NOTIONAL","minNotional":"0.01000000"},{"filterType":"MAX_NUM_ALGO_ORDERS","maxNumAlgoOrders":5}]},{"symbol":"EOSETH","status":"TRADING","baseAsset":"EOS","baseAssetPrecision":8,"quoteAsset":"ETH","quotePrecision":8,"orderTypes":["LIMIT","LIMIT_MAKER","MARKET","STOP_LOSS_LIMIT","TAKE_PROFIT_LIMIT"],"icebergAllowed":false,"filters":[{"filterType":"PRICE_FILTER","minPrice":"0.00178700","maxPrice":"0

**Comment by TheFitzZZ** [comment]
Chiming in - this started for me a few hours ago. Same issue.

**Comment by JKorf** [comment]
The Binance API has had a small update, apparently they also changed the name of the rate limit type. I'll look into it, you can expect a new version later today.

**Comment by TheFitzZZ** [comment]
For some weird reason this does not happen consistently. I just added a handling for the error, making my code retry, as I noticed that randomly it would work. Retrying seems to be a workaround till you added the fix.

Btw: thanks for all your effort here m8.

**Comment by JKorf** [comment]
I think maybe not all Binance servers are updated yet, meaning if your request gets routed to 1 it might return the old version of the data, if it gets routed to the other it might get the new data. 
Only thing I can think of why it would work sometimes.

**Comment by JKorf** [comment]
I've pushed a new version which works with the new updated API!

**Comment by TheFitzZZ** [comment]
Awesome, will test immediately :-)
Thank you!

**Comment by TheFitzZZ** [comment]
Looking good on my side!

**Comment by GustafValentine** [comment]
Hi everyone,
First of all, thank you @JKorf for your work, really much appreciated.
I'm still seeing version 3.1.13, could you push the next version including the current fix for this issue ?
Thanks ! :-)

**Comment by JKorf** [comment]
3.1.13 is the new version, are you still having problems?

**Comment by GustafValentine** [comment]
@JKorf oh I am sorry, it is now working indeed. I had tested too fast without updating all my c# projects.
Thanks a lot.
