### ISSUE TITLE
Getting BAD_PRECISION and PRICE_FILTER exceptions although AutoComply is set for TakeProfitLimit order type.

### ISSUE THREAD

**Issue by salocinx** [JKorf/Binance.Net#515]
**Describe the bug**

I have installed the latest stable version 6.4.0 with NuGet packet manager and I am using `TradeRulesBehaviour.AutoComply`.

I get `-1013: Filter failure: PRICE_FILTER` exception when trying to place the following order:

```
var result = client.Spot.Order.PlaceOrder("COMPUSDT", 
    OrderSide.Buy, OrderType.TakeProfitLimit, 
    newClientOrderId: "test-order-0001", 
    quantity: Convert.ToDecimal(0.083), 
    price: Convert.ToDecimal(148.234512345), 
    stopPrice: Convert.ToDecimal(150.2345), 
    timeInForce: TimeInForce.GoodTillCancel);
```

I get `-1111 BAD_PRECISION` exception when trying to place the following order (added some more digits at stop-price compared to the example above):

```
var result = client.Spot.Order.PlaceOrder("COMPUSDT", 
    OrderSide.Buy, OrderType.TakeProfitLimit, 
    newClientOrderId: "test-order-0001", 
    quantity: Convert.ToDecimal(0.083), 
    price: Convert.ToDecimal(148.234512345), 
    stopPrice: Convert.ToDecimal(150.234512345), 
    timeInForce: TimeInForce.GoodTillCancel);
```

**To Reproduce**

Try to place the orders above.

**Expected behavior**

With `TradeRulesBehaviour.AutoComply` set, the order should be placed without throwing an exception I guess.

**Debug logging**

Additional information to the error codes according to the [API manual](https://binance-docs.github.io/apidocs/spot/en/#11xx-2xxx-request-issues):

-1111 BAD_PRECISION: Precision is over the maximum defined for this asset.
-1013 "Filter failure: PRICE_FILTER": Price is too high, too low, and/or not following the tick size rule for the symbol.

**Thank you!!!**

**Comment by JKorf** [comment]
Price filter is something that can't be checked with auto comply, because it relies on knowing the current price for a symbol, which means having to do a request at the time you want to place the order. That's not really desirable, so the price being too high or low won't be enforced by AutoComply.

There wasn't any checking being done on StopPrice, I've added that in the latest version.

**Comment by salocinx** [comment]
Thanks for your response! Okay I will check the price filters and see if my values are within the current price range.

> There wasn't any checking being done on StopPrice, I've added that in the latest version.

Do you mean it should be resolved in the `NuGet` package revision 6.4.0 ? Or is there a pre-release available?

**Comment by salocinx** [comment]
Please let me know how I can enable logging to the console. I will then check what goes wrong on my side. Thanks.

**Comment by Kudwig** [comment]
Look at your different price filters/trade rules for 
Minimum Trade Amount
Min Price Movement
Minimum Order Size

-1111 BAD_PRECISION
Precision is over the maximum defined for this asset, thus your rounding is calculated wrong. I normally truncated it.

-1013: Filter failure: PRICE_FILTER
Is associated with order sizes. Binance somewhere publishes a list of the maximum precision allowed for each coin. Say OMG can only be traded with volumes that are rounded to the third (may be something else, just guessing) digit. Then for example buying 5.11 OMG is fine but 5.115 is not. I found that the published precision values are not quite accurate, but with rounding one digit more than required (5.1 OMG in this example) 

I hvnt used TradeRulesBehaviour.AutoComply, but i guess you want these functions to be applied automatically...for that i dont have a answer

**Comment by JKorf** [comment]
You can set the logging to write to the console using this in the client options: `LogWriters = new List<TextWriter>{ Console.Out }`. By default it will write to the Debug output, which should show up in your output window in your editor. 

The stop price should be adjusted for the precision, so I'm not sure why you're still getting an error on that. Please try the latest version, I've fixed some logging in that, so see and share what it outputs please.

**Comment by salocinx** [comment]
@Kudwig Thanks a lot for sharing your ideas and comments. I am meanwhile aware of how I could implement this myself, but I am also trying to help to fix `TradeRulesBehaviour.AutoComply` function.

@JKorf I have updated the libraries to the latest stable release and did some testing with `LogWriters` enabled. Here's the result:

```
PlaceOrder("test-order-x", 
                    "COMPUSDT", 
                    OrderSide.Buy, 
                    OrderType.TakeProfitLimit,
                    154.23457800219978, 
                    154.21997800219978, 
                    0.0834750420871074, 
                    0.0, 
                    TimeInForce.GoodTillCancel);
```

I still get the following error although the prices and quantities seem to have been clamped correctly:

```
2021/01/05 13:59:10:390 | Binance    | Info | Quantity clamped from 0.0834750420871074 to 0.08347 based on lot size filter
2021/01/05 13:59:10:391 | Binance    | Info | price floored from 154.2345780022 to 154.23 based on price filter
2021/01/05 13:59:10:391 | Binance    | Info | Stop price floored from 154.2199780022 to 154.21 based on price filter
Error -1111: Precision is over the maximum defined for this asset.
```

Thanks for your ongoing support!

**Comment by dukesteen** [comment]
@salocinx Do you have an update on this issue? I'm havi g the same problem and wondering how you solved it manually

**Comment by JKorf** [comment]
Hi this should be fixed in 6.8.0. Sorry for the delay!
